name: Validation

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - v*
    branches:
      - main

env:
  GO_VERSION: ^1.19.1
  PACKWIZ_VERSION: c7c2ca786bd050043dc36f5a35fbe7699a29adbc
  TO_VERSION: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.ref_name }}

jobs:  
  modrinth:
    name: Generate Modrinth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@${{ env.PACKWIZ_VERSION }}
      - uses: actions/checkout@v3
      - name: Cache Mods
        uses: actions/cache@v3
        with:
          path: ~/.cache/packwiz/cache
          key: mr-${{ hashFiles('mods/*') }}
      - name: Versioning
        run: sed -i "s/0.0.0-semantically-released.0/${TO_VERSION}/g" pack.toml
      - name: Generate Modrinth Pack
        run: packwiz mr export -o "TemmiesOriginsClient-${TO_VERSION}.mrpack"
      - uses: actions/upload-artifact@v3
        with:
          name: Modrinth
          path: TemmiesOriginsClient*.mrpack
          if-no-files-found: error
  
  credits:
    name: Generate Credits
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run credits
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: Credits
          path: credits.md
          if-no-files-found: error

  deploy:
    name: Deploy
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [modrinth, credits]
    steps:
      - uses: actions/download-artifact@v3
      - run: zip -ur Modrinth/TemmiesOriginsClient-*.mrpack Credits/credits.md
      - name: Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitMode: true
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          modrinth-id: P6l6LWR2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          files-primary: "Modrinth/TemmiesOriginsClient-*.mrpack"
          game-versions: "1.19.2"
          loaders: fabric

          changelog: ${{ steps.changelog.outputs.changelog }}